public enum TokenType {
    IDENTIFIER,
    KEYWORD,
    OPERATOR,
    SEPARATOR,
    COMMENT,
    NUMBER,
    FLOATING_POINT_LITERAL,
    INTEGER_LITERAL,
    BOOLEAN_LITERAL,
    NULL_LITERAL,
    CHARACTER_LITERAL,
    STRING_LITERAL,
    INCORRECT_TOKEN,
    REGEXP;

}
